server:
  port: 8080

spring:
  application:
    name: api-gateway

  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:


      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: uploads_route
          uri: lb://product-service
          predicates:
            - Path=/uploads/**
          filters:
            - StripPrefix=1
        - id: zona-service
          uri: lb://delibery-service
          predicates:
            - Path=/api/zonas/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/usuarios/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: cliente-service
          uri: lb://user-service
          predicates:
            - Path=/api/clientes/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: inventario-service
          uri: lb://inventario-service
          predicates:
            - Path=/api/inventario/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: category-service
          uri: lb://product-service
          predicates:
            - Path=/api/category/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: producto-service
          uri: lb://product-service
          predicates:
            - Path=/api/productos/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: atributo-service
          uri: lb://product-service
          predicates:
            - Path=/api/atributos/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: atributo-categoria-service
          uri: lb://product-service
          predicates:
            - Path=/api/atributo-categoria/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: producto-atributo-service
          uri: lb://product-service
          predicates:
            - Path=/api/producto-atributo/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: valor-atributo-service
          uri: lb://product-service
          predicates:
            - Path=/api/valor-atributo/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalogo/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: carrito-service
          uri: lb://carrito-service
          predicates:
            - Path=/api/carrito/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: cupones-service
          uri: lb://promotion-service
          predicates:
            - Path=/api/cupones/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: promociones-service
          uri: lb://promotion-service
          predicates:
            - Path=/api/promociones/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
        - id: user-secure
          uri: lb://user-service
          predicates:
            - Path=/api/usuarios/secure/**
            - Header=Authorization, Bearer .+
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: MiClaveSuperSecreta1234567890123456
config:
  jwt-enabled: false
